### ISSUE TITLE
[BUG] chameleon-table paginator doesn't respect overridden theme variables

### ISSUE THREAD

**Issue by ryuhhnn** [MaritzSTL/chameleon#244]
**Describe the bug**
Currently, the table header accent colour is correctly pulling from the `--color-secondary` theme variable, but the paginator is not

**To Reproduce**
add the following css to any implementation of chameleon-table:

```css
chameleon-table {
    --color-secondary: purple;
}
```

**Expected behavior**
Chameleon table paginator should be able to be overridden with the `--color-secondary` variable
